/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practical.pkg5.pkg2019;

import javax.swing.*;

/**
 *
 * @author jrago
 */
public class JForm extends javax.swing.JFrame {

    /**
     * Creates new form JForm
     */
    public JForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        value1txt = new javax.swing.JTextField();
        value2txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resultstxt = new javax.swing.JTextField();
        Subtractionbtn = new javax.swing.JButton();
        Multiplicationbtn = new javax.swing.JButton();
        Divisionbtbn = new javax.swing.JButton();
        Additionbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("A Simple Calculator");

        jLabel1.setText("1st Value (Integer Only):");

        jLabel2.setText("2nd Value (Integer Only):");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Results:");

        resultstxt.setEditable(false);
        resultstxt.setEnabled(false);

        Subtractionbtn.setText("-");
        Subtractionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractionbtnActionPerformed(evt);
            }
        });

        Multiplicationbtn.setText("*");
        Multiplicationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicationbtnActionPerformed(evt);
            }
        });

        Divisionbtbn.setText("/");
        Divisionbtbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionbtbnActionPerformed(evt);
            }
        });

        Additionbtn.setText("+");
        Additionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditionbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(value1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(value2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Additionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Subtractionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Multiplicationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Divisionbtbn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3)
                        .addGap(77, 77, 77)
                        .addComponent(resultstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(value1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Subtractionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Additionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Divisionbtbn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Multiplicationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(value2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(resultstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void AdditionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditionbtnActionPerformed
        int a = 0;
        int b = 0;
        String msg;
        try{
            a = Integer.parseInt(((JTextField)this.value1txt).getText());
            b = Integer.parseInt(((JTextField)this.value2txt).getText());
        }
        catch(NumberFormatException e){
            msg = "Value entered is not valid.";
            display(msg);
        }
        ((JTextField)this.resultstxt).setText(Integer.toString(a+b));
    }//GEN-LAST:event_AdditionbtnActionPerformed

    private void SubtractionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractionbtnActionPerformed
        int a = 0;
        int b = 0;
        String msg;
        try{
            a = Integer.parseInt(((JTextField)this.value1txt).getText());
            b = Integer.parseInt(((JTextField)this.value2txt).getText());
        }
        catch(NumberFormatException e){
            msg = "Value entered is not valid.";
            display(msg);
        }
        ((JTextField)this.resultstxt).setText(Integer.toString(a-b));
    }//GEN-LAST:event_SubtractionbtnActionPerformed

    private void MultiplicationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicationbtnActionPerformed
        int a = 0;
        int b = 0;
        String msg;
        try{
            a = Integer.parseInt(((JTextField)this.value1txt).getText());
            b = Integer.parseInt(((JTextField)this.value2txt).getText());
        }
        catch(NumberFormatException e){
            msg = "Value entered is not valid.";
            display(msg);
        }
        ((JTextField)this.resultstxt).setText(Integer.toString(a*b));
    }//GEN-LAST:event_MultiplicationbtnActionPerformed

    private void DivisionbtbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionbtbnActionPerformed
        int a = 0;
        int b = 0;
        int c = 0;
        String msg;
        try{
            a = Integer.parseInt(((JTextField)this.value1txt).getText());
            b = Integer.parseInt(((JTextField)this.value2txt).getText());
        }
        catch(NumberFormatException e){
            msg = "Value entered is not valid.";
            display(msg);
        }
        try{
            c=a/b;
        }
        catch(ArithmeticException e){
            msg = "Cannot divide by ZERO.";
            display(msg);
        }
        ((JTextField)this.resultstxt).setText(Integer.toString(c));
    }//GEN-LAST:event_DivisionbtbnActionPerformed
    
    public void display (String msg){
        JOptionPane.showMessageDialog(null, msg);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JForm().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Additionbtn;
    private javax.swing.JButton Divisionbtbn;
    private javax.swing.JButton Multiplicationbtn;
    private javax.swing.JButton Subtractionbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField resultstxt;
    private javax.swing.JTextField value1txt;
    private javax.swing.JTextField value2txt;
    // End of variables declaration//GEN-END:variables
}
